arm:
  type: ur10
  initial_joint_states:
    linear_arm_actuator_joint: 0
# sensors:
#   logical_camera_1:
#     type: logical_camera
#     pose:
#       xyz: [-0.7, -0.15, 3.5]
#       rpy: [0, 'pi/2', 0]
sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0, 0.5, 5]
      rpy: [0, 'pi/2', 0]
